### ISSUE TITLE
Game is slow

### ISSUE THREAD

**Issue by Omegalpha44** [Omegalpha44/Game_Of_Life-charlesDUVAL-4#1]
Because of the usage of tkinter, the interface is quite slow right now. 
Perhaps a way to boost it would be delighteful.

**Comment by anis-hentit** [comment]
#6  have made a different implementation that runs faster thanks to multi threading and using PIL to draw the texture in one go instead of doing it by block

**Comment by Omegalpha44** [comment]
I've added you code as another file, because there are too much changes ! Thanks !
